name: build and publish nuget release
on: workflow_dispatch
  
jobs:

  build_and_publish_nuget_release:

    runs-on: windows-latest 
    
    permissions:
      repository-projects: write
      packages: write
      contents: write
      
    steps:

    - name: checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: pack project
      run: dotnet pack
      working-directory: PowerCollections
    - name: publish packed project
      run: dotnet nuget push "PowerCollections\bin\Debug\*.nupkg" -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/DashaBabaylova/index.json --skip-duplicate
      working-directory: PowerCollections
    - name: Get XML
      id: getxml
      uses: mavrosxristoforos/get-xml-info@1.1.1
      with: 
        xml-file: 'PowerCollections/PowerCollections/PowerCollections.csproj'
        xpath: '//Version'  
    - name: release project
      uses: ncipollo/release-action@v1.12.0
      with: 
        artifacts: 'PowerCollections\PowerCollections\bin\Debug\*${{ steps.getxml.outputs.info }}.nupkg'
        tag: 'v${{ steps.getxml.outputs.info }}'
